"use client";
import React, { useState, useTransition } from "react";
import { updateSupervisorOrganizations } from "@/features/supervisor-shifts/actions";
import type { ToastState } from "@/components/dashboard/users/user-toast";
import type { Dictionary } from "@/i18n/dictionaries";
type Props = { open: boolean; onOpenChange: (open: boolean) => void; supervisor: any | null; organizations: any[]; currentOrgAssignments: any[]; onToast: (toast: ToastState) => void; dictionary?: Dictionary["dashboard"]["supervisorShifts"] };
export function EditOrganizationsDialog({ open, onOpenChange, supervisor, organizations, currentOrgAssignments, onToast, dictionary }: Props) {
  const [isPending, startTransition] = useTransition(); const [selectedOrgs, setSelectedOrgs] = useState<string[]>([]); const [startDate, setStartDate] = useState(""); const text = dictionary!.dialogs;
  React.useEffect(() => { if (open && supervisor) { setSelectedOrgs(currentOrgAssignments.filter((a) => a.supervisor_id === supervisor.id).map((a) => a.organization_id)); setStartDate(new Date().toISOString().split("T")[0]); } }, [open, supervisor, currentOrgAssignments]);
  if (!open || !supervisor) return null;
  const handleSubmit = (event: React.FormEvent) => { event.preventDefault(); if (selectedOrgs.length === 0) { onToast({ message: text.selectAtLeastOneOrganization, tone: "error" }); return; } if (!startDate) { onToast({ message: text.effectiveRequired, tone: "error" }); return; } startTransition(async () => { try { await updateSupervisorOrganizations(supervisor.id, selectedOrgs, startDate); onToast({ message: text.success, tone: "success" }); onOpenChange(false); } catch (error: any) { onToast({ message: error.message || text.unexpectedError, tone: "error" }); } }); };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-md rounded-xl bg-white p-6 shadow-lg"><div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-bold text-navy">{text.organizations}</h2><button onClick={() => onOpenChange(false)} disabled={isPending} className="text-muted">✕</button></div><form onSubmit={handleSubmit} className="space-y-4"><label className="block text-sm font-medium text-navy">{dictionary!.supervisor}<input value={supervisor.full_name} readOnly className="mt-1 w-full rounded-md border border-border bg-surface px-3 py-2 text-sm" /></label><div><label className="mb-2 block text-sm font-medium text-navy">{text.organizations}</label><div className="max-h-60 space-y-2 overflow-y-auto rounded-md border border-border p-3">{organizations.map((org) => <label key={org.id} className="flex items-center gap-2"><input type="checkbox" checked={selectedOrgs.includes(org.id)} disabled={isPending} onChange={() => setSelectedOrgs((current) => current.includes(org.id) ? current.filter((id) => id !== org.id) : [...current, org.id])} /><span>{org.name}</span></label>)}{organizations.length === 0 ? <div className="py-2 text-center text-sm text-muted">{text.noOrganizations}</div> : null}</div></div><label className="block text-sm font-medium text-navy">{text.effectiveDate}<input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} disabled={isPending} required className="mt-1 w-full rounded-md border border-border px-3 py-2 text-sm" /></label><div className="flex justify-end gap-3 border-t border-border pt-4"><button type="button" onClick={() => onOpenChange(false)} disabled={isPending} className="rounded-md bg-surface px-4 py-2 text-sm">{text.cancel}</button><button type="submit" disabled={isPending} className="rounded-md bg-primary px-4 py-2 text-sm text-white">{isPending ? text.saving : text.save}</button></div></form></div></div>;
}
