"use client";
import React, { useState, useTransition } from "react";
import { ShiftTemplateFormDialog } from "./shift-template-form-dialog";
import { toggleShiftTemplateStatus } from "@/features/supervisor-shifts/actions";
import { calculateShiftDurations } from "@/features/supervisor-shifts/utils";
import type { ToastState } from "@/components/dashboard/users/user-toast";
import type { Dictionary } from "@/i18n/dictionaries";
type Props = { open: boolean; onOpenChange: (open: boolean) => void; shifts: any[]; onToast: (toast: ToastState) => void; dictionary?: Dictionary["dashboard"]["supervisorShifts"] };
export function ManageShiftsDialog({ open, onOpenChange, shifts, onToast, dictionary }: Props) {
  const [isPending, startTransition] = useTransition(); const [isFormOpen, setIsFormOpen] = useState(false); const [editingShift, setEditingShift] = useState<any | null>(null); if (!open) return null; const text = dictionary!.dialogs;
  const toggle = (shift: any) => startTransition(async () => { try { await toggleShiftTemplateStatus(shift.id, !shift.is_active); onToast({ message: text.success, tone: "success" }); } catch (error: any) { onToast({ message: error.message || text.unexpectedError, tone: "error" }); } });
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="flex max-h-[90vh] w-full max-w-2xl flex-col rounded-xl bg-white p-6 shadow-lg"><div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-bold text-navy">{text.manageTitle}</h2><button onClick={() => onOpenChange(false)} className="text-muted">✕</button></div><div className="min-h-0 flex-1 overflow-y-auto"><table className="w-full text-start text-sm"><thead className="sticky top-0 border-b border-border bg-surface/50 text-muted"><tr>{[text.name, text.from, text.to, text.workDays, text.status, dictionary!.actions].map((label) => <th key={label} className="px-4 py-2 text-start font-semibold">{label}</th>)}</tr></thead><tbody className="divide-y divide-border">{shifts.length === 0 ? <tr><td colSpan={6} className="py-8 text-center text-muted">{text.noShift}</td></tr> : shifts.map((shift) => <tr key={shift.id}><td className="px-4 py-3 text-navy"><div className="font-medium">{shift.name}</div>{shift.break_start_time && shift.break_end_time ? <div className="mt-1 text-xs text-muted">{dictionary!.breakLabel}: {shift.break_start_time.substring(0, 5)} - {shift.break_end_time.substring(0, 5)}<br />{dictionary!.netLabel}: {calculateShiftDurations(shift.start_time, shift.end_time, shift.break_start_time, shift.break_end_time).formattedNet}</div> : null}</td><td className="px-4 py-3 text-muted">{shift.start_time.substring(0, 5)}</td><td className="px-4 py-3 text-muted">{shift.end_time.substring(0, 5)}</td><td className="px-4 py-3 text-muted">{shift.work_days.length} {text.workDays}</td><td className="px-4 py-3">{shift.is_active ? <span className="text-success">{text.active}</span> : <span className="text-muted">{text.inactive}</span>}</td><td className="space-x-2 px-4 py-3"><button type="button" onClick={() => { setEditingShift(shift); setIsFormOpen(true); }} disabled={isPending} className="text-xs font-medium text-primary">{text.edit}</button><button type="button" onClick={() => toggle(shift)} disabled={isPending} className="text-xs font-medium text-primary">{shift.is_active ? text.deactivate : text.activate}</button></td></tr>)}</tbody></table></div><div className="mt-6 flex justify-between border-t pt-4"><button type="button" onClick={() => { setEditingShift(null); setIsFormOpen(true); }} className="text-sm font-medium text-primary">{text.addShift}</button><button type="button" onClick={() => onOpenChange(false)} className="rounded-md bg-surface px-4 py-2 text-sm font-medium text-navy">{text.close}</button></div></div><ShiftTemplateFormDialog open={isFormOpen} onOpenChange={setIsFormOpen} shiftToEdit={editingShift} onToast={onToast} dictionary={dictionary} /></div>;
}
