-- Driver App authentication Phase 1.
--
-- The visible login identifier is the existing public.drivers.keeta_driver_id
-- value. Supabase Auth uses an internal implementation-only email generated by
-- the server; passwords remain exclusively in Supabase Auth.

alter table public.drivers
  add column if not exists auth_user_id uuid null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'drivers_auth_user_id_fkey'
      and conrelid = 'public.drivers'::regclass
  ) then
    alter table public.drivers
      add constraint drivers_auth_user_id_fkey
      foreign key (auth_user_id)
      references auth.users(id)
      on delete set null;
  end if;
end
$$;

create unique index if not exists drivers_auth_user_id_key
  on public.drivers (auth_user_id)
  where auth_user_id is not null;

comment on column public.drivers.auth_user_id is
  'Optional link to the Supabase Auth user used by the separate Driver PWA. One Auth user belongs to one driver; passwords are stored only in Supabase Auth.';

alter table public.profiles
  add column if not exists must_change_password boolean not null default false;

comment on column public.profiles.must_change_password is
  'When true, the application must require this user to change a temporary password after login.';

create unique index if not exists drivers_global_keeta_driver_id_key
  on public.drivers ((btrim(keeta_driver_id)))
  where nullif(btrim(coalesce(keeta_driver_id, '')), '') is not null;

comment on index public.drivers_global_keeta_driver_id_key is
  'Global uniqueness for the Driver App visible login identifier, reusing drivers.keeta_driver_id.';

alter table public.organization_user_permissions
  drop constraint if exists organization_user_permissions_key_check;

alter table public.organization_user_permissions
  add constraint organization_user_permissions_key_check check (
    permission_key in (
      'organization.dashboard.view',
      'drivers.view',
      'drivers.create',
      'drivers.update',
      'drivers.status',
      'drivers.archive',
      'drivers.documents.view',
      'drivers.documents.download',
      'drivers.activity.view',
      'drivers.account.manage',
      'driver_reports.view',
      'driver_reports.import',
      'driver_reports.replace',
      'driver_reports.details.view',
      'fleet.cars.view',
      'fleet.motorcycles.view',
      'fleet.create',
      'fleet.update',
      'fleet.technical_status',
      'fleet.operational_status',
      'fleet.archive',
      'fleet.operating_card.download',
      'fleet.activity.view'
    )
  );

insert into public.organization_user_permissions (
  user_id,
  organization_id,
  permission_key,
  granted_by,
  updated_by
)
select
  oa.user_id,
  oa.organization_id,
  'drivers.account.manage',
  oa.user_id,
  oa.user_id
from public.organization_access oa
where oa.access_level = 'manage'::public.organization_access_level
on conflict (user_id, organization_id, permission_key) do nothing;

create or replace function public.replace_managed_user_organization_permissions(
  p_actor_user_id uuid,
  p_target_user_id uuid,
  p_access jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_target_role public.app_role;
  v_target_home_organization_id uuid;
  v_access_item jsonb;
  v_organization_id uuid;
  v_permission_keys text[];
  v_permission_key text;
  v_old_permissions text[];
  v_new_permissions text[];
  v_access_level public.organization_access_level;
  v_seen_organizations uuid[] := array[]::uuid[];
  v_view_permissions constant text[] := array[
    'organization.dashboard.view',
    'drivers.view',
    'driver_reports.view',
    'fleet.cars.view',
    'fleet.motorcycles.view'
  ];
  v_all_permissions constant text[] := array[
    'organization.dashboard.view',
    'drivers.view',
    'drivers.create',
    'drivers.update',
    'drivers.status',
    'drivers.archive',
    'drivers.documents.view',
    'drivers.documents.download',
    'drivers.activity.view',
    'drivers.account.manage',
    'driver_reports.view',
    'driver_reports.import',
    'driver_reports.replace',
    'driver_reports.details.view',
    'fleet.cars.view',
    'fleet.motorcycles.view',
    'fleet.create',
    'fleet.update',
    'fleet.technical_status',
    'fleet.operational_status',
    'fleet.archive',
    'fleet.operating_card.download',
    'fleet.activity.view'
  ];
begin
  if not public.is_system_owner_user(p_actor_user_id) then
    raise exception 'Managed user permissions update failed: unauthorized.';
  end if;

  if p_actor_user_id = p_target_user_id then
    raise exception 'Managed user permissions update failed: self operation is not allowed.';
  end if;

  select p.role, p.home_organization_id
    into v_target_role, v_target_home_organization_id
  from public.profiles p
  where p.id = p_target_user_id
    and p.deleted_at is null;

  if v_target_role is null then
    raise exception 'Managed user permissions update failed: target is unavailable.';
  end if;

  if v_target_role = 'system_owner'::public.app_role then
    raise exception 'Managed user permissions update failed: target is protected.';
  end if;

  if jsonb_typeof(p_access) <> 'array' then
    raise exception 'Managed user permissions update failed: access must be an array.';
  end if;

  if v_target_role = 'driver'::public.app_role and jsonb_array_length(p_access) > 0 then
    raise exception 'Managed user permissions update failed: drivers cannot receive additional access.';
  end if;

  for v_access_item in select * from jsonb_array_elements(p_access)
  loop
    if not (v_access_item ? 'organization_id') or not (v_access_item ? 'permission_keys') then
      raise exception 'Managed user permissions update failed: malformed access entry.';
    end if;

    v_organization_id := (v_access_item ->> 'organization_id')::uuid;

    if v_organization_id = any(v_seen_organizations) then
      raise exception 'Managed user permissions update failed: duplicate organization.';
    end if;
    v_seen_organizations := array_append(v_seen_organizations, v_organization_id);

    if v_organization_id = v_target_home_organization_id then
      raise exception 'Managed user permissions update failed: home organization cannot be additional access.';
    end if;

    if not exists (
      select 1 from public.organizations o
      where o.id = v_organization_id
        and o.is_active = true
    ) then
      raise exception 'Managed user permissions update failed: organization inactive or missing.';
    end if;

    select coalesce(array_agg(distinct value order by value), array[]::text[])
      into v_permission_keys
    from jsonb_array_elements_text(v_access_item -> 'permission_keys') as keys(value);

    foreach v_permission_key in array v_permission_keys
    loop
      if not v_permission_key = any(v_all_permissions) then
        raise exception 'Managed user permissions update failed: invalid permission key.';
      end if;
    end loop;
  end loop;

  for v_organization_id in
    select oa.organization_id
    from public.organization_access oa
    where oa.user_id = p_target_user_id
      and (
        jsonb_array_length(p_access) = 0
        or not exists (
          select 1
          from jsonb_array_elements(p_access) item
          where (item ->> 'organization_id')::uuid = oa.organization_id
        )
      )
  loop
    select coalesce(array_agg(permission_key order by permission_key), array[]::text[])
      into v_old_permissions
    from public.organization_user_permissions
    where user_id = p_target_user_id
      and organization_id = v_organization_id;

    delete from public.organization_user_permissions
    where user_id = p_target_user_id
      and organization_id = v_organization_id;

    delete from public.organization_access
    where user_id = p_target_user_id
      and organization_id = v_organization_id;

    insert into public.activity_logs (
      action,
      actor_user_id,
      target_user_id,
      organization_id,
      entity_type,
      entity_id,
      before_data,
      after_data,
      metadata
    )
    values (
      'user_permissions_updated',
      p_actor_user_id,
      p_target_user_id,
      v_organization_id,
      'profile',
      p_target_user_id,
      jsonb_build_object('access_enabled', true, 'permission_keys', v_old_permissions),
      jsonb_build_object('access_enabled', false, 'permission_keys', array[]::text[]),
      jsonb_build_object('changed_permissions', true)
    );
  end loop;

  for v_access_item in select * from jsonb_array_elements(p_access)
  loop
    v_organization_id := (v_access_item ->> 'organization_id')::uuid;

    select coalesce(array_agg(permission_key order by permission_key), array[]::text[])
      into v_old_permissions
    from public.organization_user_permissions
    where user_id = p_target_user_id
      and organization_id = v_organization_id;

    select coalesce(array_agg(distinct value order by value), array[]::text[])
      into v_new_permissions
    from jsonb_array_elements_text(v_access_item -> 'permission_keys') as keys(value);

    v_access_level :=
      case
        when v_new_permissions <@ v_view_permissions then 'view'::public.organization_access_level
        else 'manage'::public.organization_access_level
      end;

    insert into public.organization_access (user_id, organization_id, access_level)
    values (p_target_user_id, v_organization_id, v_access_level)
    on conflict (user_id, organization_id) do update
      set access_level = excluded.access_level,
          updated_at = timezone('utc', now());

    delete from public.organization_user_permissions
    where user_id = p_target_user_id
      and organization_id = v_organization_id;

    foreach v_permission_key in array v_new_permissions
    loop
      insert into public.organization_user_permissions (
        user_id,
        organization_id,
        permission_key,
        granted_by,
        updated_by
      )
      values (
        p_target_user_id,
        v_organization_id,
        v_permission_key,
        p_actor_user_id,
        p_actor_user_id
      );
    end loop;

    insert into public.activity_logs (
      action,
      actor_user_id,
      target_user_id,
      organization_id,
      entity_type,
      entity_id,
      before_data,
      after_data,
      metadata
    )
    values (
      'user_permissions_updated',
      p_actor_user_id,
      p_target_user_id,
      v_organization_id,
      'profile',
      p_target_user_id,
      jsonb_build_object('access_enabled', cardinality(v_old_permissions) > 0, 'permission_keys', v_old_permissions),
      jsonb_build_object('access_enabled', true, 'permission_keys', v_new_permissions),
      jsonb_build_object(
        'added_permissions',
        (select coalesce(jsonb_agg(value), '[]'::jsonb) from unnest(v_new_permissions) value where not value = any(v_old_permissions)),
        'removed_permissions',
        (select coalesce(jsonb_agg(value), '[]'::jsonb) from unnest(v_old_permissions) value where not value = any(v_new_permissions))
      )
    );
  end loop;
end;
$$;

revoke all on function public.replace_managed_user_organization_permissions(uuid, uuid, jsonb)
  from public, anon, authenticated;
grant execute on function public.replace_managed_user_organization_permissions(uuid, uuid, jsonb)
  to service_role;

drop policy if exists drivers_select_representative_self on public.drivers;
create policy drivers_select_representative_self
  on public.drivers
  for select
  to authenticated
  using (
    auth_user_id = auth.uid()
    and exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role = 'driver'::public.app_role
        and p.status = 'active'::public.account_status
        and p.deleted_at is null
    )
  );

grant select on table public.drivers to service_role;
grant update (auth_user_id) on table public.drivers to service_role;
grant select on table public.profiles to service_role;
grant update (must_change_password) on table public.profiles to service_role;
